# Generated by Django 5.2.9 on 2026-03-27 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmbienteSena', '0003_ingreso'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ingreso',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='cuentadante',
            unique_together={('instructor', 'ambiente')},
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='elementos',
        ),
        migrations.AddField(
            model_name='cuentadante',
            name='ambiente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='AmbienteSena.ambiente'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='instructor',
            name='Cedula',
            field=models.IntegerField(),
        ),
        migrations.RemoveField(
            model_name='cuentadante',
            name='elemento',
        ),
    ]
