# Generated by Django 5.2.9 on 2026-03-27 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmbienteSena', '0004_alter_ingreso_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuentadante',
            options={'managed': True},
        ),
        migrations.AlterUniqueTogether(
            name='cuentadante',
            unique_together=set(),
        ),
    ]
